### ISSUE TITLE
burp安装失败

### ISSUE THREAD

**Issue by j1dag** [Anof-cyber/PyCript#1]
![image](https://user-images.githubusercontent.com/73382341/217469510-2b5c4a57-5a5f-4f29-b7f5-b3fb8d3518f0.png)
![image](https://user-images.githubusercontent.com/73382341/217469519-413347f2-a56c-4d89-aa57-eaff160d0bea.png)
jython也是2.7.0的版本，是因为我的java版本低了，他报错“ImportError: cannot import name io”吗？

**Comment by Anof-cyber** [comment]
The error is from the Jython 2.7.0. Could you try Jython 2.7.2 or Jython [2.7.3](https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.3/jython-standalone-2.7.3.jar)
