### ISSUE TITLE
Some settings don't persist across Burp restarts

### ISSUE THREAD

**Issue by YSaxon** [Anof-cyber/PyCript#12]
Presently, some PyCript settings persist through restarting Burp, such as "Request/Response Encryption Decryption Files", but others don't such as the "Request/Response Type" radio buttons, and need to be set again every time. Could you please add the calls to saveExtensionSetting https://github.com/Anof-cyber/PyCript/blob/c2652f39381e488bd16d10901792f78bc1433b91/pycript.py#L1094 and loadExtensionSetting https://github.com/Anof-cyber/PyCript/blob/c2652f39381e488bd16d10901792f78bc1433b91/pycript.py#L374 to those settings that don't have it?

**Comment by YSaxon** [comment]
Let me know if you'd like me to make a pull request

**Comment by Anof-cyber** [comment]
Sure, I don't think its a big change we can add this as well. If you have added this ,you can create a pull
