### ISSUE TITLE
JSON payload includes an extra space when using python scripts

### ISSUE THREAD

**Issue by Draoken** [Anof-cyber/PyCript#7]
**Have you gone through the Documentation or Video Tutorial**
 - Documentation - https://pycript.souravkalal.tech/
 - Video - https://youtu.be/J8KE5VR8yDk?si=yr4XqqwWh5ms7O6s
 - [Y/N] - Y

**Describe the bug**
When you use the automatic encryption feature with Python along with the Request Type of parameter value, the resulting payload adds an additional space in the json body causing an error. It is between the key and the value (after the colon). 

**To Reproduce**
1. Configure settings similar to screenshot below
2. Use automatic encrypt function with a JSON request
3. Observe the extra space in the resulting request in the Logger/Comparer tab of BurpSuite

**Expected behavior**
An extra space should not be added, the payload should sit exactly in the same spot as before.
This is not an issue with the encrypting script, as the resulting payload is exactly correct. Removing the space causes the request to successfully pass. 

**Screenshots**
![image](https://github.com/Anof-cyber/PyCript/assets/10473010/eaff9160-49bc-4592-b565-d8e27e86b156)
![image](https://github.com/Anof-cyber/PyCript/assets/10473010/fce44610-65a5-436d-bf7d-44b58a5d424e)

**Desktop (please complete the following information):**
 - PyCript Version .3

**Comment by Anof-cyber** [comment]
Is it possible to share the json request body (if you can update the value with dummy value).

Also can you confirm if it only happens with auto encrypt? Or is it same when click on pycript tab in repeater.

By default pycript tries to beautify the json, can you check if its same in raw and pretty within request.

**Comment by Draoken** [comment]
It is the same when you click on pycript tab in repeater.

![image](https://github.com/Anof-cyber/PyCript/assets/10473010/9b89f3ed-67e7-40fa-916e-f10eb4865b72)

I found the exact spot that I was able to fix the issue. The red highlight is where it's adding a space, and I added my "fix" below it in green. I'm sure you can find something more elegant than what I did.

![image](https://github.com/Anof-cyber/PyCript/assets/10473010/d24b0e81-ef3a-4cf6-852a-8168236ae0d1)

**Comment by Anof-cyber** [comment]
Just for reference, can you confirm if the back-end application/API (the one you are working on in the screenshot) gives any error if space are there.

Its a default python JSON behaviour to add spaces when json.dump is used.

**Comment by Draoken** [comment]
Yes, that's why I had to fix it this as the space was breaking the server response
